### ISSUE TITLE
Regole del gruppo

### ISSUE THREAD

**Issue by MattiaFailla** [sorcio/python-italia-telegram-bot#2]
Ciao ragazzi, mi potete inoltrare la lista delle regole del gruppo? Vorrei aggiungerle ad Electus_bot.

**Comment by sorcio** [comment]
Non esiste una lista di regole, ma esiste un [codice di condotta](https://github.com/pythonitalia/code-of-conducts/blob/master/online/italian.md) che è comune agli spazi comunitari di Python Italia

**Comment by MattiaFailla** [comment]
Bene, implemento immediatamente il codice di condotta.
Passo e chiudo
