### ISSUE TITLE
Warn, kick e ban

### ISSUE THREAD

**Issue by MattiaFailla** [sorcio/python-italia-telegram-bot#3]
Ciao, 
bisogna definire delle regole e dei pattern per i warn, i kick e i ban.
Le tre categorie sono in ordine di importanza.

Se qualcuno di voi vuole prepare una lista di "keyword" per le tre categorie mi farebbe un grosso piacere.

**Comment by sorcio** [comment]
Cosa intendi per keyword?

**Comment by MattiaFailla** [comment]
> Cosa intendi per keyword?

Trigger o parole che non devono comparire nella chat e/o immagini e comportamenti indesiderati che possono portare al kick o al ban.

**Comment by sorcio** [comment]
Per il momento eviterei di definirne.

**Comment by Kavuti** [comment]
Questa domanda la porrei in generale a tutti gli admin del gruppo, magari insieme tirano fuori qualcosa che possiamo poi utilizzare.

**Comment by MattiaFailla** [comment]
Chiudo issue dati gli sviluppi delle discussioni degli altri issue.
