### ISSUE TITLE
ERROR - An uncaught error was raised while running the promise in markdown help module

### ISSUE THREAD

**Issue by MattiaFailla** [sorcio/python-italia-telegram-bot#4]
The markdown help module needs a review due to internal server error while handling the response message for the command /markdownhelp

The following error is raised:
```
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/USER/modules/misc.py", line 348, in markdown_help
    update.effective_message.reply_text(MARKDOWN_HELP, parse_mode=ParseMode.HTML)
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/message.py", line 455, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: unclosed end tag at byte offset 247

```

**Comment by Kavuti** [comment]
Pare che al bot sia arrivato un input mal formattato... si verifica spesso?

**Comment by MattiaFailla** [comment]
Non spesso, si è verificato solo in due occasioni: 
- Server Telegram occupato
- In markdown help (probabilmente per un errore nell'handling del comando)

Bisogna rivedere il codice dell'handler e la stringa di help.

**Comment by Kavuti** [comment]
I server di Telegram hanno quindi difficoltà a gestire tutte le richieste dei bot? 😨

**Comment by MattiaFailla** [comment]
> I server di Telegram hanno quindi difficoltà a gestire tutte le richieste dei bot? 😨

Penso di essere stato sfortunato io, non credo ci siano grossi problemi di questo tipo.

**Comment by Kavuti** [comment]
A me il markdown in generale ha dato problemi già all'avvio del bot. Ho modificato il la ParseMode in __main__.py:146 da MARKDOWN a HTML e sembra che ora a me funzioni. Siamo sicuri ci serva il MARKDOWN?

**Comment by iflare3g** [comment]
Alla fine raggiungono lo stesso scopo, con sintassi diversa quindi penso sia indifferente, secondo me

**Comment by MattiaFailla** [comment]
In alcuni moduli è necessario per formattare i bottoni o i link!

**Comment by iflare3g** [comment]
Almeno dalla doc sembrano equivalenti, sintassi a parte.
La formattazione in quei moduli non può essere convertita usando HTML se Markdown crea gravi problemi ? 
Chiedo perchè non mi è mai capitata una situazione di questo tipo

**Comment by MattiaFailla** [comment]
Chiudo e sposto l'issue sulla repo di @Kavuti
